/**
 * WORLD EXPLORER — beta data file
 * -------------------------------
 * This is placeholder/demo content, not verified travel data.
 * Ratings are an illustrative 1–10 scoring system invented for this beta
 * (source: "editorial estimate"), NOT pulled from any external survey or
 * dataset. Costs are rough, rounded estimates for demo purposes only.
 * Swap this file out for a real API or CMS once you're past the beta stage —
 * every field below is exactly what the rendering code in app.js expects,
 * so you can replace values without touching app.js.
 */

const COUNTRIES = [
  {
    id: "japan",
    name: "Japan",
    flag: "🇯🇵",
    capital: "Tokyo",
    coords: { lat: 35.6762, lng: 139.6503 },
    continent: "Asia",
    population: "123.9 million",
    languages: ["Japanese"],
    currency: "Japanese yen (JPY)",
    teaser: "Neon cities, quiet temples, and trains that leave on the second.",
    ratingSource: "editorial estimate",
    ratings: {
      overall: 9,
      naturalBeauty: 8,
      culture: 10,
      food: 10,
      safety: 10,
      affordability: 5,
      nightlife: 7,
      publicTransport: 10,
    },
    attractions: [
      { name: "Fushimi Inari Shrine", city: "Kyoto", type: "Temples & religious sites", blurb: "Thousands of vermilion torii gates climbing the mountainside." },
      { name: "Shibuya Crossing", city: "Tokyo", type: "Cities", blurb: "The world's busiest pedestrian scramble, best seen from above." },
      { name: "Arashiyama Bamboo Grove", city: "Kyoto", type: "Natural wonders", blurb: "A quiet green corridor of towering bamboo stalks." },
    ],
    costs: { budget: 70, midRange: 150, luxury: 350, currencySymbol: "$" },
    bestTime: "Late March–April (cherry blossoms) or October–November (autumn colour)",
    funFact: "Japan has more than 5.5 million vending machines — roughly one for every 23 people.",
  },
  {
    id: "italy",
    name: "Italy",
    flag: "🇮🇹",
    capital: "Rome",
    coords: { lat: 41.9028, lng: 12.4964 },
    continent: "Europe",
    population: "59 million",
    languages: ["Italian"],
    currency: "Euro (EUR)",
    teaser: "Ruins, coastline, and dinner that's never in a hurry.",
    ratingSource: "editorial estimate",
    ratings: {
      overall: 9,
      naturalBeauty: 8,
      culture: 10,
      food: 10,
      safety: 7,
      affordability: 6,
      nightlife: 7,
      publicTransport: 6,
    },
    attractions: [
      { name: "Colosseum", city: "Rome", type: "Historical sites", blurb: "The largest amphitheatre ever built, still standing after 2,000 years." },
      { name: "Cinque Terre", city: "Liguria", type: "Natural wonders", blurb: "Five cliffside fishing villages linked by coastal trails." },
      { name: "Uffizi Gallery", city: "Florence", type: "Museums", blurb: "Renaissance masterpieces by Botticelli, da Vinci, and Michelangelo." },
    ],
    costs: { budget: 65, midRange: 140, luxury: 320, currencySymbol: "$" },
    bestTime: "April–June or September–October, before and after peak summer crowds",
    funFact: "Italy has more UNESCO World Heritage Sites than any other country.",
  },
  {
    id: "thailand",
    name: "Thailand",
    flag: "🇹🇭",
    capital: "Bangkok",
    coords: { lat: 13.7563, lng: 100.5018 },
    continent: "Asia",
    population: "71.6 million",
    languages: ["Thai"],
    currency: "Thai baht (THB)",
    teaser: "Golden temples, street-food stalls, and islands built for slowing down.",
    ratingSource: "editorial estimate",
    ratings: {
      overall: 8,
      naturalBeauty: 9,
      culture: 8,
      food: 9,
      safety: 6,
      affordability: 9,
      nightlife: 8,
      publicTransport: 6,
    },
    attractions: [
      { name: "Wat Arun", city: "Bangkok", type: "Temples & religious sites", blurb: "The 'Temple of Dawn', clad in porcelain and coloured glass." },
      { name: "Railay Beach", city: "Krabi", type: "Beaches", blurb: "A limestone-cliff peninsula reachable only by boat." },
      { name: "Chiang Mai Old City", city: "Chiang Mai", type: "Cities", blurb: "A moated grid of lantern-lit temples and night markets." },
    ],
    costs: { budget: 35, midRange: 80, luxury: 220, currencySymbol: "$" },
    bestTime: "November–February, the cool, dry season",
    funFact: "Thailand is the only Southeast Asian country never colonised by a European power.",
  },
  {
    id: "france",
    name: "France",
    flag: "🇫🇷",
    capital: "Paris",
    coords: { lat: 48.8566, lng: 2.3522 },
    continent: "Europe",
    population: "68.4 million",
    languages: ["French"],
    currency: "Euro (EUR)",
    teaser: "Grand boulevards, countryside vineyards, and a museum on every corner.",
    ratingSource: "editorial estimate",
    ratings: {
      overall: 9,
      naturalBeauty: 8,
      culture: 10,
      food: 10,
      safety: 7,
      affordability: 5,
      nightlife: 8,
      publicTransport: 9,
    },
    attractions: [
      { name: "Eiffel Tower", city: "Paris", type: "Cities", blurb: "The iron landmark that redefined the Paris skyline in 1889." },
      { name: "Mont Saint-Michel", city: "Normandy", type: "Historical sites", blurb: "A fortified abbey rising from tidal flats." },
      { name: "Palace of Versailles", city: "Versailles", type: "Historical sites", blurb: "The gilded former seat of the French monarchy." },
    ],
    costs: { budget: 75, midRange: 160, luxury: 380, currencySymbol: "$" },
    bestTime: "April–June or September–October",
    funFact: "France is the most-visited country in the world by international tourist arrivals.",
  },
  {
    id: "mexico",
    name: "Mexico",
    flag: "🇲🇽",
    capital: "Mexico City",
    coords: { lat: 19.4326, lng: -99.1332 },
    continent: "North America",
    population: "128.9 million",
    languages: ["Spanish"],
    currency: "Mexican peso (MXN)",
    teaser: "Ancient pyramids, colourful colonial towns, and coastline on two oceans.",
    ratingSource: "editorial estimate",
    ratings: {
      overall: 8,
      naturalBeauty: 9,
      culture: 9,
      food: 9,
      safety: 5,
      affordability: 8,
      nightlife: 8,
      publicTransport: 5,
    },
    attractions: [
      { name: "Chichén Itzá", city: "Yucatán", type: "Historical sites", blurb: "A Maya step-pyramid complex and modern Wonder of the World." },
      { name: "Tulum Ruins", city: "Quintana Roo", type: "Historical sites", blurb: "Clifftop Maya ruins overlooking the Caribbean Sea." },
      { name: "Guanajuato", city: "Guanajuato", type: "Cities", blurb: "A hillside colonial city of candy-coloured alleys and tunnels." },
    ],
    costs: { budget: 40, midRange: 90, luxury: 240, currencySymbol: "$" },
    bestTime: "December–April, the dry season",
    funFact: "Mexico is home to 35 UNESCO World Heritage Sites, more than any other country in the Americas.",
  },
  {
    id: "iceland",
    name: "Iceland",
    flag: "🇮🇸",
    capital: "Reykjavík",
    coords: { lat: 64.1466, lng: -21.9426 },
    continent: "Europe",
    population: "390,000",
    languages: ["Icelandic"],
    currency: "Icelandic króna (ISK)",
    teaser: "Glaciers, geysers, and skies that turn green after dark.",
    ratingSource: "editorial estimate",
    ratings: {
      overall: 8,
      naturalBeauty: 10,
      culture: 6,
      food: 6,
      safety: 10,
      affordability: 3,
      nightlife: 5,
      publicTransport: 4,
    },
    attractions: [
      { name: "Gullfoss", city: "Golden Circle", type: "Natural wonders", blurb: "A two-tiered waterfall that seems to drop into the earth itself." },
      { name: "Jökulsárlón", city: "South Coast", type: "Natural wonders", blurb: "A lagoon of drifting icebergs calved from a glacier." },
      { name: "Blue Lagoon", city: "Reykjanes", type: "Natural wonders", blurb: "A geothermal spa set in a black lava field." },
    ],
    costs: { budget: 110, midRange: 220, luxury: 480, currencySymbol: "$" },
    bestTime: "June–August for daylight, February–March for the northern lights",
    funFact: "Iceland runs almost entirely on renewable geothermal and hydroelectric power.",
  },
];

// Quick lookup helper used by app.js
const getCountryById = (id) => COUNTRIES.find((c) => c.id === id);
